services:
  clickr-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      QUARKUS_HTTP_HOST: 0.0.0.0
      DB_URL: postgresql://clickr-postgres:5432/clickrdb?search_path=core
      DB_USERNAME: clickr
      DB_PASSWORD: clickr
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - '8080:8080'
    networks:
      - clickr-network
  postgres:
    platform: linux/amd64
    image: postgres:18-alpine
    container_name: clickr-postgres
    environment:
      POSTGRES_DB: clickrdb
      POSTGRES_USER: clickr
      POSTGRES_PASSWORD: clickr
    ports:
      - "5432:5432"
    networks:
      - clickr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clickr"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  clickr-network:
